### PR TITLE
Fix AHP command and compatibility with Discord Integration

### PR DESCRIPTION
**Pull request by Parkeymon**
Updated to exiled 2.8.0. Fixed AHP and discord integration conflict with `di` command and replaced it with `ditem`

### CODE REVIEW

**Comment by PintTheDragon** [comment]
Le troll

**Comment by PintTheDragon** [comment]
#4

**Comment by Parkeymon** [comment]
> #4

doesnt fix ahp

**Comment by thomasjosif** [comment]
I'll manually cherry-pick changes as it conflicts with #4 

Thanks for the PR though!

**Pull request closed without merging**
